
# ██╗  ██╗███████╗██╗     ██╗██╗  ██╗
# ██║  ██║██╔════╝██║     ██║╚██╗██╔╝
# ███████║█████╗  ██║     ██║ ╚███╔╝ 
# ██╔══██║██╔══╝  ██║     ██║ ██╔██╗ 
# ██║  ██║███████╗███████╗██║██╔╝ ██╗
# ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝╚═╝  ╚═╝
                                                                                 
theme = "catppuccin_frappe"

[editor]
line-number = "relative"
cursorline = true
popup-border = "all"
mouse = true
rulers = [120]
bufferline = "always"
auto-format = true
end-of-line-diagnostics = "hint" #Minimum severity to show diagnostics
continue-comments = false # auto comment on newline if on comment

[editor.inline-diagnostics]
cursor-line = "hint" # minimum severity to show on current line, hidden while in insert-mode
# other-lines = "error" 

# Show new line symbol
[editor.whitespace.render] 
# newline = "all"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
select = "underline"
insert = "bar"

[editor.lsp]
display-inlay-hints = false
display-messages = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "version-control"] 
right = ["diagnostics", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"] # deselect and keep primary cursor only
tab = "goto_next_function" # select and jump to the next function via TreeSitter
S-tab = "goto_prev_function" # select and jump to the previous function via TreeSitter
end = "goto_line_end_newline" # stops at linebreak
C-end = "goto_line_end" # goes to line end, Ctrl-End
del = ["move_next_word_end", "move_prev_word_end", "move_next_word_end", "delete_selection_noyank"] # delete current word
ins = "insert_mode"
G = "goto_file_end" #Like vim, Shift-G
ret = ["move_line_down", "goto_line_start"]
S-ret = ["move_line_up", "goto_line_start"]
space.i = ":toggle lsp.display-inlay-hints" # toggle inlay hints with <Space>-i

[keys.insert]
ins = "normal_mode"

[editor.file-picker]
hidden = false
